[package]
name = "bevy-xp"
version = "0.1.0"
edition = "2021"


[lints.rust]
unsafe-code = "forbid"
unused = "allow"       # DEV

[dependencies]
bevy = { version = "0.12.1", features = ["wayland"] }
rand = "0.8.5"
